# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cors-reverse-proxy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '10.14'

    - name: npm install, build, and test
      run: |
        npm install
        npm audit fix
        npm run build --if-present
        npm run test --if-present

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'cors-reverse-proxy'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0de8dc4b72bf4d63add5eee179c21c18 }}
        package: .
